// Code generated by httphandlergen. DO NOT EDIT
package controller

import (
	"encoding/json"
	"fmt"
	"net/http"
)

func (r *UserController) createHandlerFunc(w http.ResponseWriter, req *http.Request) {
	var requestBody newUserRequest
	err := json.NewDecoder(req.Body).Decode(&requestBody)
	if err != nil {
		panic(err)
	}

	resp, err := r.create(req, requestBody)
	if err != nil {
		panic(err)
	}

	err = json.NewEncoder(w).Encode(resp)
	if err != nil {
		panic(err)
	}
}
